export enum JourneyActionsType {
  FETCH_JOURNEY = "FETCH_JOURNEY",
  FETCH_JOURNEY_SUCCESS = "FETCH_JOURNEY_SUCCESS",
  FETCH_JOURNEY_ERROR = "FETCH_JOURNEY_ERROR",

  CREATE_JOURNEY = "CREATE_JOURNEY",
  CREATE_JOURNEY_SUCCESS = "CREATE_JOURNEY_SUCCESS",
  CREATE_JOURNEY_ERROR = "CREATE_JOURNEY_ERROR",

  UPDATE_JOURNEY = "UPDATE_JOURNEY",
  UPDATE_JOURNEY_SUCCESS = "UPDATE_JOURNEY_SUCCESS",
  UPDATE_JOURNEY_ERROR = "UPDATE_JOURNEY_ERROR",

  CLOSE_JOURNEY = "CLOSE_JOURNEY",
  CLOSE_JOURNEY_SUCCESS = "CLOSE_JOURNEY_SUCCESS",
  CLOSE_JOURNEY_ERROR = "CLOSE_JOURNEY_ERROR",
}
