export enum PlayerActionsType {
  FETCH_PLAYER = "FETCH_PLAYER",
  FETCH_PLAYER_SUCCESS = "FETCH_PLAYER_SUCCESS",
  FETCH_PLAYER_ERROR = "FETCH_PLAYER_ERROR",

  CREATE_PLAYER = "CREATE_PLAYER",
  CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS",
  CREATE_PLAYER_ERROR = "CREATE_PLAYER_ERROR",

  UPDATE_PLAYER = "UPDATE_PLAYER",
  UPDATE_PLAYER_SUCCESS = "UPDATE_PLAYER_SUCCESS",
  UPDATE_PLAYER_ERROR = "UPDATE_PLAYER_ERROR",

}
