import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Lexend } from "next/font/google";
import "./globals.css";

import { Header, Footer, ToastContainer } from "@/components";

const lexend = Lexend({
  variable: "--font-lexend-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased`}>
        <SessionProvider>
          <div className="flex flex-col min-h-screen">
            <Header />

            {children}

            <Footer />
          </div>
        </SessionProvider>
        <ToastContainer />
        <div id="modal" />
        <div id="menu" />
      </body>
    </html>
  );
}
