export enum SeasonActionsType {
  CREATE_SEASON = "CREATE_SEASON",
  CREATE_SEASON_SUCCESS = "CREATE_SEASON_SUCCESS",
  CREATE_SEASON_ERROR = "CREATE_SEASON_ERROR",

  UPDATE_SEASON = "UPDATE_SEASON",
  UPDATE_SEASON_SUCCESS = "UPDATE_SEASON_SUCCESS",
  UPDATE_SEASON_ERROR = "UPDATE_SEASON_ERROR",

  FETCH_SEASON = "FETCH_SEASON",
  FETCH_SEASON_SUCCESS = "FETCH_SEASON_SUCCESS",
  FETCH_SEASON_ERROR = "FETCH_SEASON_ERROR",

  LOAD_OPENED_SEASON = "LOAD_OPENED_SEASON",
  LOAD_OPENED_SEASON_SUCCESS = "LOAD_OPENED_SEASON_SUCCESS",
  LOAD_OPENED_SEASON_ERROR = "LOAD_OPENED_SEASON_ERROR",

  LOAD_STORAGE_DATA = "LOAD_STORAGE_DATA",
  LOAD_STORAGE_DATA_SUCCESS = "LOAD_STORAGE_DATA_SUCCESS",
  LOAD_STORAGE_DATA_ERROR = "LOAD_STORAGE_DATA_ERROR",
}
